// Code generated by sqlc. DO NOT EDIT.

package model

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Member struct {
	ID       uuid.UUID      `json:"id"`
	Name     string         `json:"name"`
	Username string         `json:"username"`
	Password string         `json:"password"`
	Email    string         `json:"email"`
	Twitter  sql.NullString `json:"twitter"`
	Github   sql.NullString `json:"github"`
	Linkedin sql.NullString `json:"linkedin"`
	CreateAt time.Time      `json:"create_at"`
	UpdateAt time.Time      `json:"update_at"`
}
