version: '2'
services:
  postgres:
    image: postgres
    restart: always
    container_name: kodein_postgres
    environment:
      - POSTGRES_USER=kodein
      - POSTGRES_PASSWORD=developmentpass
      - POSTGRES_DB=kodein
    ports:
      - '5433:5432'
    volumes:
      - ../db/data:/var/lib/postgresql/data
  redis:
    image: redis
    restart: always
    container_name: kodein_redis
    ports:
      - '6379:6379'
