version: '2'
services:
  postgres:
    image: postgres
    restart: always
    container_name: kodein_postgres
    environment:
      - POSTGRES_USER=kodein
      - POSTGRES_PASSWORD=developmentpass
      - POSTGRES_DB=kodein
    ports:
      - '5433:5432'
    volumes:
      - ../db/data:/var/lib/postgresql/data
  redis:
    image: redis
    restart: always
    container_name: kodein_redis
    ports:
      - '6379:6379'
  nsqlookupd:
    image: nsqio/nsq
    container_name: kodein_nsqlookupd
    command: /nsqlookupd
    ports:
      - '4160:4160'
      - '4161:4161'
  nsqd:
    image: nsqio/nsq
    container_name: kodein_nsqd
    command: /nsqd --broadcast-address=nsqd --lookupd-tcp-address=nsqlookupd:4160
    depends_on:
      - nsqlookupd
    ports:
      - '4150:4150'
      - '4151:4151'
  nsqadmin:
    image: nsqio/nsq
    container_name: kodein_nsqadmin
    command: /nsqadmin --lookupd-http-address=nsqlookupd:4161
    depends_on:
      - nsqlookupd
    ports:
      - '4171:4171'
